name: CI
 
on:
    workflow_dispatch:
    push:
      branches: ["main"]
 
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
 
jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.dotnet.name }}
    runs-on: ubuntu-22.04
     
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Linux, rid: linux-x64 }
        - { name: Windows, rid: win-x64 }
        dotnet:
        - { name: .NET 8, version: '8.0.x' }
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup .NET ${{ matrix.dotnet.version }} SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - name: Enforce SDK Version
        run: dotnet new globaljson --sdk-version ${{ steps.setup-dotnet.outputs.dotnet-version }} --force
      - name: Verify SDK Installation
        run: dotnet --info
      - name: Restore
        run: dotnet restore
#      - name: Build
#        run: dotnet build --configuration Release --no-restore
#      - name: Test
#        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish -r ${{ matrix.platform.rid }} --self-contained --artifacts-path ./artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VRCTally ${{ matrix.platform.name }} ${{ matrix.dotnet.name }}
          path: './artifacts'
